//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.26 at 09:42:26 PM EST 
//


package com.project.soap.webservices.gameservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.soap.webservices.gameservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetGamesListRequest_QNAME = new QName("http://com/project/soap/webservices/gameservice", "GetGamesListRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.soap.webservices.gameservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGamesListResponse }
     * 
     */
    public GetGamesListResponse createGetGamesListResponse() {
        return new GetGamesListResponse();
    }

    /**
     * Create an instance of {@link GetGamesTypeRequest }
     * 
     */
    public GetGamesTypeRequest createGetGamesTypeRequest() {
        return new GetGamesTypeRequest();
    }

    /**
     * Create an instance of {@link GetGamesTypeResponse }
     * 
     */
    public GetGamesTypeResponse createGetGamesTypeResponse() {
        return new GetGamesTypeResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://com/project/soap/webservices/gameservice", name = "GetGamesListRequest")
    public JAXBElement<Object> createGetGamesListRequest(Object value) {
        return new JAXBElement<Object>(_GetGamesListRequest_QNAME, Object.class, null, value);
    }

}
