//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.25 at 09:24:48 PM EST 
//


package com.project.soap.webservices.gameservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.soap.webservices.gameservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.soap.webservices.gameservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGamesListRequest }
     * 
     */
    public GetGamesListRequest createGetGamesListRequest() {
        return new GetGamesListRequest();
    }

    /**
     * Create an instance of {@link GetGamesTypeRequest }
     * 
     */
    public GetGamesTypeRequest createGetGamesTypeRequest() {
        return new GetGamesTypeRequest();
    }

    /**
     * Create an instance of {@link GetGamesListResponse }
     * 
     */
    public GetGamesListResponse createGetGamesListResponse() {
        return new GetGamesListResponse();
    }

    /**
     * Create an instance of {@link GetGamesTypeResponse }
     * 
     */
    public GetGamesTypeResponse createGetGamesTypeResponse() {
        return new GetGamesTypeResponse();
    }

}
