//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.25 at 09:51:42 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/project/soap/webservices/helloservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.project.soap.webservices.helloservice;
